# =====================================================================
#                            APP KONFIGURATION
# =====================================================================

title = "Meine Testanwendung"
version = "1.4.2"
debug = true